version: "3.9"

services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: vertrieb
      POSTGRES_USER: vertrieb
      POSTGRES_PASSWORD: vertrieb
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      # === Entra ID / Microsoft Identity Platform ===
      ENTRA_TENANT_ID: ${ENTRA_TENANT_ID}
      ENTRA_CLIENT_ID: ${ENTRA_CLIENT_ID}
      ENTRA_CLIENT_SECRET: ${ENTRA_CLIENT_SECRET}
      OAUTH_REDIRECT_URI: ${OAUTH_REDIRECT_URI:-http://localhost:8000/auth/callback}
      SESSION_SECRET: ${SESSION_SECRET:-change-me-in-.env}
      # === DB ===
      DATABASE_URL: ${DATABASE_URL:-postgresql+psycopg2://vertrieb:vertrieb@db:5432/vertrieb}
      # === CSV path ===
      CUSTOMERS_CSV_PATH: ${CUSTOMERS_CSV_PATH:-/app/data/customers.csv}
      # === Default locale ===
      DEFAULT_LOCALE: ${DEFAULT_LOCALE:-de}
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--proxy-headers"]

volumes:
  db_data:
